# Generated by Django 3.1.2 on 2020-11-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
